# Generated by Django 4.1.4 on 2023-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_db',
            old_name='oder_id',
            new_name='Exicuted_orderId',
        ),
        migrations.AddField(
            model_name='order_db',
            name='Exicuted_p',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_db',
            name='order_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_db',
            name='qty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_db',
            name='symbol',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
