# Generated by Django 4.1.4 on 2023-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_rename_oder_id_order_db_exicuted_orderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='profit_Loss_amnt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
