# Generated by Django 4.1.4 on 2023-02-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0003_order_db_profit_loss_amnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='CE_OI',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
