# Generated by Django 4.1.4 on 2023-02-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0005_order_db_ce_iv_order_db_pe_iv_order_db_pe_oi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='CE_VOLM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_db',
            name='PE_VOLM',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
