# Generated by Django 4.1.4 on 2023-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0006_order_db_ce_volm_order_db_pe_volm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='Date_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
