# Generated by Django 4.1.4 on 2023-03-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0007_order_db_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intruction_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_target', models.CharField(max_length=100, null=True)),
                ('weekly_target', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
