# Generated by Django 4.1.4 on 2023-03-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0008_intruction_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruction_db',
            name='date_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
