# Generated by Django 4.1.4 on 2023-03-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0009_intruction_db_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruction_db',
            name='trading_plans',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
