# Generated by Django 4.1.4 on 2023-03-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0011_mood_thought_status_db_alter_intruction_db_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='Market_condition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_db',
            name='Mood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_db',
            name='Preparation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_db',
            name='Thought',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
