# Generated by Django 4.1.4 on 2023-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0012_order_db_market_condition_order_db_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intruction_db',
            name='date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mood_thought_status_db',
            name='date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_db',
            name='PE_VOLM',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
